apiVersion: apps/v1
kind: Deployment
metadata:
  name: based-webapp-deployment
  namespace: {{ .Values.namespace }}
  labels: 
    app: based-webapp
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: based-webapp
  template:
    metadata:
      labels:
        app: based-webapp
    spec:
      containers:
        - name: based-webapp
          image: harbor.sch.bme.hu/personal-valentin/based-webapp:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: PROSODY_HOST
              value: "https://xmpp.basedware.xyz"
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 350m
              memory: 400Mi
      imagePullSecrets:
        - name: harbor-registry
