apiVersion: v1
kind: Service
metadata:
  name: based-webapp-service
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: based.lan
spec:
  selector:
    app: based-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
