apiVersion: v1
kind: Service
metadata:
  name: docosaurus-service
  namespace: {{ .Values.namespace }}
    annotations:
    external-dns.alpha.kubernetes.io/hostname: blog.lan
spec:
  selector:
    app: docosaurus-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
