apiVersion: v1
kind: Service
metadata:
  name: currently-playing-webapp-service
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: currently-playing.lan
spec:
  selector:
    app: currently-playing-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
